language: java
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploying $RELEASE_PKG_FILE"
deploy:
  provider: releases
  api_key: "${GH_API_KEY}"
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  draft: true
  on:
    tags: true